package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i route256/checkout/internal/clients/grpc/loms_client.LomsService -o ./mocks/loms_service_minimock.go -n LomsServiceMock

import (
	"context"
	"route256/checkout/internal/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// LomsServiceMock implements loms_client.LomsService
type LomsServiceMock struct {
	t minimock.Tester

	funcCreateOrder          func(ctx context.Context, user int64, items []*model.OrderItem) (i1 int64, err error)
	inspectFuncCreateOrder   func(ctx context.Context, user int64, items []*model.OrderItem)
	afterCreateOrderCounter  uint64
	beforeCreateOrderCounter uint64
	CreateOrderMock          mLomsServiceMockCreateOrder

	funcStocks          func(ctx context.Context, sku uint32) (spa1 []*model.Stock, err error)
	inspectFuncStocks   func(ctx context.Context, sku uint32)
	afterStocksCounter  uint64
	beforeStocksCounter uint64
	StocksMock          mLomsServiceMockStocks
}

// NewLomsServiceMock returns a mock for loms_client.LomsService
func NewLomsServiceMock(t minimock.Tester) *LomsServiceMock {
	m := &LomsServiceMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateOrderMock = mLomsServiceMockCreateOrder{mock: m}
	m.CreateOrderMock.callArgs = []*LomsServiceMockCreateOrderParams{}

	m.StocksMock = mLomsServiceMockStocks{mock: m}
	m.StocksMock.callArgs = []*LomsServiceMockStocksParams{}

	return m
}

type mLomsServiceMockCreateOrder struct {
	mock               *LomsServiceMock
	defaultExpectation *LomsServiceMockCreateOrderExpectation
	expectations       []*LomsServiceMockCreateOrderExpectation

	callArgs []*LomsServiceMockCreateOrderParams
	mutex    sync.RWMutex
}

// LomsServiceMockCreateOrderExpectation specifies expectation struct of the LomsService.CreateOrder
type LomsServiceMockCreateOrderExpectation struct {
	mock    *LomsServiceMock
	params  *LomsServiceMockCreateOrderParams
	results *LomsServiceMockCreateOrderResults
	Counter uint64
}

// LomsServiceMockCreateOrderParams contains parameters of the LomsService.CreateOrder
type LomsServiceMockCreateOrderParams struct {
	ctx   context.Context
	user  int64
	items []*model.OrderItem
}

// LomsServiceMockCreateOrderResults contains results of the LomsService.CreateOrder
type LomsServiceMockCreateOrderResults struct {
	i1  int64
	err error
}

// Expect sets up expected params for LomsService.CreateOrder
func (mmCreateOrder *mLomsServiceMockCreateOrder) Expect(ctx context.Context, user int64, items []*model.OrderItem) *mLomsServiceMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsServiceMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsServiceMockCreateOrderExpectation{}
	}

	mmCreateOrder.defaultExpectation.params = &LomsServiceMockCreateOrderParams{ctx, user, items}
	for _, e := range mmCreateOrder.expectations {
		if minimock.Equal(e.params, mmCreateOrder.defaultExpectation.params) {
			mmCreateOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateOrder.defaultExpectation.params)
		}
	}

	return mmCreateOrder
}

// Inspect accepts an inspector function that has same arguments as the LomsService.CreateOrder
func (mmCreateOrder *mLomsServiceMockCreateOrder) Inspect(f func(ctx context.Context, user int64, items []*model.OrderItem)) *mLomsServiceMockCreateOrder {
	if mmCreateOrder.mock.inspectFuncCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("Inspect function is already set for LomsServiceMock.CreateOrder")
	}

	mmCreateOrder.mock.inspectFuncCreateOrder = f

	return mmCreateOrder
}

// Return sets up results that will be returned by LomsService.CreateOrder
func (mmCreateOrder *mLomsServiceMockCreateOrder) Return(i1 int64, err error) *LomsServiceMock {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsServiceMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsServiceMockCreateOrderExpectation{mock: mmCreateOrder.mock}
	}
	mmCreateOrder.defaultExpectation.results = &LomsServiceMockCreateOrderResults{i1, err}
	return mmCreateOrder.mock
}

// Set uses given function f to mock the LomsService.CreateOrder method
func (mmCreateOrder *mLomsServiceMockCreateOrder) Set(f func(ctx context.Context, user int64, items []*model.OrderItem) (i1 int64, err error)) *LomsServiceMock {
	if mmCreateOrder.defaultExpectation != nil {
		mmCreateOrder.mock.t.Fatalf("Default expectation is already set for the LomsService.CreateOrder method")
	}

	if len(mmCreateOrder.expectations) > 0 {
		mmCreateOrder.mock.t.Fatalf("Some expectations are already set for the LomsService.CreateOrder method")
	}

	mmCreateOrder.mock.funcCreateOrder = f
	return mmCreateOrder.mock
}

// When sets expectation for the LomsService.CreateOrder which will trigger the result defined by the following
// Then helper
func (mmCreateOrder *mLomsServiceMockCreateOrder) When(ctx context.Context, user int64, items []*model.OrderItem) *LomsServiceMockCreateOrderExpectation {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsServiceMock.CreateOrder mock is already set by Set")
	}

	expectation := &LomsServiceMockCreateOrderExpectation{
		mock:   mmCreateOrder.mock,
		params: &LomsServiceMockCreateOrderParams{ctx, user, items},
	}
	mmCreateOrder.expectations = append(mmCreateOrder.expectations, expectation)
	return expectation
}

// Then sets up LomsService.CreateOrder return parameters for the expectation previously defined by the When method
func (e *LomsServiceMockCreateOrderExpectation) Then(i1 int64, err error) *LomsServiceMock {
	e.results = &LomsServiceMockCreateOrderResults{i1, err}
	return e.mock
}

// CreateOrder implements loms_client.LomsService
func (mmCreateOrder *LomsServiceMock) CreateOrder(ctx context.Context, user int64, items []*model.OrderItem) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmCreateOrder.beforeCreateOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateOrder.afterCreateOrderCounter, 1)

	if mmCreateOrder.inspectFuncCreateOrder != nil {
		mmCreateOrder.inspectFuncCreateOrder(ctx, user, items)
	}

	mm_params := &LomsServiceMockCreateOrderParams{ctx, user, items}

	// Record call args
	mmCreateOrder.CreateOrderMock.mutex.Lock()
	mmCreateOrder.CreateOrderMock.callArgs = append(mmCreateOrder.CreateOrderMock.callArgs, mm_params)
	mmCreateOrder.CreateOrderMock.mutex.Unlock()

	for _, e := range mmCreateOrder.CreateOrderMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmCreateOrder.CreateOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateOrder.CreateOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateOrder.CreateOrderMock.defaultExpectation.params
		mm_got := LomsServiceMockCreateOrderParams{ctx, user, items}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateOrder.t.Errorf("LomsServiceMock.CreateOrder got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateOrder.CreateOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateOrder.t.Fatal("No results are set for the LomsServiceMock.CreateOrder")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmCreateOrder.funcCreateOrder != nil {
		return mmCreateOrder.funcCreateOrder(ctx, user, items)
	}
	mmCreateOrder.t.Fatalf("Unexpected call to LomsServiceMock.CreateOrder. %v %v %v", ctx, user, items)
	return
}

// CreateOrderAfterCounter returns a count of finished LomsServiceMock.CreateOrder invocations
func (mmCreateOrder *LomsServiceMock) CreateOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.afterCreateOrderCounter)
}

// CreateOrderBeforeCounter returns a count of LomsServiceMock.CreateOrder invocations
func (mmCreateOrder *LomsServiceMock) CreateOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.beforeCreateOrderCounter)
}

// Calls returns a list of arguments used in each call to LomsServiceMock.CreateOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateOrder *mLomsServiceMockCreateOrder) Calls() []*LomsServiceMockCreateOrderParams {
	mmCreateOrder.mutex.RLock()

	argCopy := make([]*LomsServiceMockCreateOrderParams, len(mmCreateOrder.callArgs))
	copy(argCopy, mmCreateOrder.callArgs)

	mmCreateOrder.mutex.RUnlock()

	return argCopy
}

// MinimockCreateOrderDone returns true if the count of the CreateOrder invocations corresponds
// the number of defined expectations
func (m *LomsServiceMock) MinimockCreateOrderDone() bool {
	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateOrderMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateOrder != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		return false
	}
	return true
}

// MinimockCreateOrderInspect logs each unmet expectation
func (m *LomsServiceMock) MinimockCreateOrderInspect() {
	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsServiceMock.CreateOrder with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateOrderMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		if m.CreateOrderMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to LomsServiceMock.CreateOrder")
		} else {
			m.t.Errorf("Expected call to LomsServiceMock.CreateOrder with params: %#v", *m.CreateOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateOrder != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		m.t.Error("Expected call to LomsServiceMock.CreateOrder")
	}
}

type mLomsServiceMockStocks struct {
	mock               *LomsServiceMock
	defaultExpectation *LomsServiceMockStocksExpectation
	expectations       []*LomsServiceMockStocksExpectation

	callArgs []*LomsServiceMockStocksParams
	mutex    sync.RWMutex
}

// LomsServiceMockStocksExpectation specifies expectation struct of the LomsService.Stocks
type LomsServiceMockStocksExpectation struct {
	mock    *LomsServiceMock
	params  *LomsServiceMockStocksParams
	results *LomsServiceMockStocksResults
	Counter uint64
}

// LomsServiceMockStocksParams contains parameters of the LomsService.Stocks
type LomsServiceMockStocksParams struct {
	ctx context.Context
	sku uint32
}

// LomsServiceMockStocksResults contains results of the LomsService.Stocks
type LomsServiceMockStocksResults struct {
	spa1 []*model.Stock
	err  error
}

// Expect sets up expected params for LomsService.Stocks
func (mmStocks *mLomsServiceMockStocks) Expect(ctx context.Context, sku uint32) *mLomsServiceMockStocks {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LomsServiceMock.Stocks mock is already set by Set")
	}

	if mmStocks.defaultExpectation == nil {
		mmStocks.defaultExpectation = &LomsServiceMockStocksExpectation{}
	}

	mmStocks.defaultExpectation.params = &LomsServiceMockStocksParams{ctx, sku}
	for _, e := range mmStocks.expectations {
		if minimock.Equal(e.params, mmStocks.defaultExpectation.params) {
			mmStocks.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStocks.defaultExpectation.params)
		}
	}

	return mmStocks
}

// Inspect accepts an inspector function that has same arguments as the LomsService.Stocks
func (mmStocks *mLomsServiceMockStocks) Inspect(f func(ctx context.Context, sku uint32)) *mLomsServiceMockStocks {
	if mmStocks.mock.inspectFuncStocks != nil {
		mmStocks.mock.t.Fatalf("Inspect function is already set for LomsServiceMock.Stocks")
	}

	mmStocks.mock.inspectFuncStocks = f

	return mmStocks
}

// Return sets up results that will be returned by LomsService.Stocks
func (mmStocks *mLomsServiceMockStocks) Return(spa1 []*model.Stock, err error) *LomsServiceMock {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LomsServiceMock.Stocks mock is already set by Set")
	}

	if mmStocks.defaultExpectation == nil {
		mmStocks.defaultExpectation = &LomsServiceMockStocksExpectation{mock: mmStocks.mock}
	}
	mmStocks.defaultExpectation.results = &LomsServiceMockStocksResults{spa1, err}
	return mmStocks.mock
}

// Set uses given function f to mock the LomsService.Stocks method
func (mmStocks *mLomsServiceMockStocks) Set(f func(ctx context.Context, sku uint32) (spa1 []*model.Stock, err error)) *LomsServiceMock {
	if mmStocks.defaultExpectation != nil {
		mmStocks.mock.t.Fatalf("Default expectation is already set for the LomsService.Stocks method")
	}

	if len(mmStocks.expectations) > 0 {
		mmStocks.mock.t.Fatalf("Some expectations are already set for the LomsService.Stocks method")
	}

	mmStocks.mock.funcStocks = f
	return mmStocks.mock
}

// When sets expectation for the LomsService.Stocks which will trigger the result defined by the following
// Then helper
func (mmStocks *mLomsServiceMockStocks) When(ctx context.Context, sku uint32) *LomsServiceMockStocksExpectation {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LomsServiceMock.Stocks mock is already set by Set")
	}

	expectation := &LomsServiceMockStocksExpectation{
		mock:   mmStocks.mock,
		params: &LomsServiceMockStocksParams{ctx, sku},
	}
	mmStocks.expectations = append(mmStocks.expectations, expectation)
	return expectation
}

// Then sets up LomsService.Stocks return parameters for the expectation previously defined by the When method
func (e *LomsServiceMockStocksExpectation) Then(spa1 []*model.Stock, err error) *LomsServiceMock {
	e.results = &LomsServiceMockStocksResults{spa1, err}
	return e.mock
}

// Stocks implements loms_client.LomsService
func (mmStocks *LomsServiceMock) Stocks(ctx context.Context, sku uint32) (spa1 []*model.Stock, err error) {
	mm_atomic.AddUint64(&mmStocks.beforeStocksCounter, 1)
	defer mm_atomic.AddUint64(&mmStocks.afterStocksCounter, 1)

	if mmStocks.inspectFuncStocks != nil {
		mmStocks.inspectFuncStocks(ctx, sku)
	}

	mm_params := &LomsServiceMockStocksParams{ctx, sku}

	// Record call args
	mmStocks.StocksMock.mutex.Lock()
	mmStocks.StocksMock.callArgs = append(mmStocks.StocksMock.callArgs, mm_params)
	mmStocks.StocksMock.mutex.Unlock()

	for _, e := range mmStocks.StocksMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.spa1, e.results.err
		}
	}

	if mmStocks.StocksMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStocks.StocksMock.defaultExpectation.Counter, 1)
		mm_want := mmStocks.StocksMock.defaultExpectation.params
		mm_got := LomsServiceMockStocksParams{ctx, sku}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStocks.t.Errorf("LomsServiceMock.Stocks got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStocks.StocksMock.defaultExpectation.results
		if mm_results == nil {
			mmStocks.t.Fatal("No results are set for the LomsServiceMock.Stocks")
		}
		return (*mm_results).spa1, (*mm_results).err
	}
	if mmStocks.funcStocks != nil {
		return mmStocks.funcStocks(ctx, sku)
	}
	mmStocks.t.Fatalf("Unexpected call to LomsServiceMock.Stocks. %v %v", ctx, sku)
	return
}

// StocksAfterCounter returns a count of finished LomsServiceMock.Stocks invocations
func (mmStocks *LomsServiceMock) StocksAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStocks.afterStocksCounter)
}

// StocksBeforeCounter returns a count of LomsServiceMock.Stocks invocations
func (mmStocks *LomsServiceMock) StocksBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStocks.beforeStocksCounter)
}

// Calls returns a list of arguments used in each call to LomsServiceMock.Stocks.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStocks *mLomsServiceMockStocks) Calls() []*LomsServiceMockStocksParams {
	mmStocks.mutex.RLock()

	argCopy := make([]*LomsServiceMockStocksParams, len(mmStocks.callArgs))
	copy(argCopy, mmStocks.callArgs)

	mmStocks.mutex.RUnlock()

	return argCopy
}

// MinimockStocksDone returns true if the count of the Stocks invocations corresponds
// the number of defined expectations
func (m *LomsServiceMock) MinimockStocksDone() bool {
	for _, e := range m.StocksMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StocksMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStocks != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		return false
	}
	return true
}

// MinimockStocksInspect logs each unmet expectation
func (m *LomsServiceMock) MinimockStocksInspect() {
	for _, e := range m.StocksMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsServiceMock.Stocks with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StocksMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		if m.StocksMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to LomsServiceMock.Stocks")
		} else {
			m.t.Errorf("Expected call to LomsServiceMock.Stocks with params: %#v", *m.StocksMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStocks != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		m.t.Error("Expected call to LomsServiceMock.Stocks")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LomsServiceMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockCreateOrderInspect()

		m.MinimockStocksInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LomsServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LomsServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateOrderDone() &&
		m.MinimockStocksDone()
}
