global:
  scrape_interval: 2s
  scrape_timeout: 2s
  evaluation_interval: 1s # Evaluate rules

rule_files:

scrape_configs:
  - job_name: "app"
    static_configs:
      - targets:
          - "loms:8081"
          - "checkout:8082"
          - "notifications:8083"