package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i route256/checkout/internal/repository/db_repository/transactor.TransactionManager -o ./mocks/transaction_manager_minimock.go -n TransactionManagerMock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// TransactionManagerMock implements transactor.TransactionManager
type TransactionManagerMock struct {
	t minimock.Tester

	funcRunRepeatableRead          func(ctx context.Context, f func(ctxTX context.Context) error) (err error)
	inspectFuncRunRepeatableRead   func(ctx context.Context, f func(ctxTX context.Context) error)
	afterRunRepeatableReadCounter  uint64
	beforeRunRepeatableReadCounter uint64
	RunRepeatableReadMock          mTransactionManagerMockRunRepeatableRead
}

// NewTransactionManagerMock returns a mock for transactor.TransactionManager
func NewTransactionManagerMock(t minimock.Tester) *TransactionManagerMock {
	m := &TransactionManagerMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.RunRepeatableReadMock = mTransactionManagerMockRunRepeatableRead{mock: m}
	m.RunRepeatableReadMock.callArgs = []*TransactionManagerMockRunRepeatableReadParams{}

	return m
}

type mTransactionManagerMockRunRepeatableRead struct {
	mock               *TransactionManagerMock
	defaultExpectation *TransactionManagerMockRunRepeatableReadExpectation
	expectations       []*TransactionManagerMockRunRepeatableReadExpectation

	callArgs []*TransactionManagerMockRunRepeatableReadParams
	mutex    sync.RWMutex
}

// TransactionManagerMockRunRepeatableReadExpectation specifies expectation struct of the TransactionManager.RunRepeatableRead
type TransactionManagerMockRunRepeatableReadExpectation struct {
	mock    *TransactionManagerMock
	params  *TransactionManagerMockRunRepeatableReadParams
	results *TransactionManagerMockRunRepeatableReadResults
	Counter uint64
}

// TransactionManagerMockRunRepeatableReadParams contains parameters of the TransactionManager.RunRepeatableRead
type TransactionManagerMockRunRepeatableReadParams struct {
	ctx context.Context
	f   func(ctxTX context.Context) error
}

// TransactionManagerMockRunRepeatableReadResults contains results of the TransactionManager.RunRepeatableRead
type TransactionManagerMockRunRepeatableReadResults struct {
	err error
}

// Expect sets up expected params for TransactionManager.RunRepeatableRead
func (mmRunRepeatableRead *mTransactionManagerMockRunRepeatableRead) Expect(ctx context.Context, f func(ctxTX context.Context) error) *mTransactionManagerMockRunRepeatableRead {
	if mmRunRepeatableRead.mock.funcRunRepeatableRead != nil {
		mmRunRepeatableRead.mock.t.Fatalf("TransactionManagerMock.RunRepeatableRead mock is already set by Set")
	}

	if mmRunRepeatableRead.defaultExpectation == nil {
		mmRunRepeatableRead.defaultExpectation = &TransactionManagerMockRunRepeatableReadExpectation{}
	}

	mmRunRepeatableRead.defaultExpectation.params = &TransactionManagerMockRunRepeatableReadParams{ctx, f}
	for _, e := range mmRunRepeatableRead.expectations {
		if minimock.Equal(e.params, mmRunRepeatableRead.defaultExpectation.params) {
			mmRunRepeatableRead.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRunRepeatableRead.defaultExpectation.params)
		}
	}

	return mmRunRepeatableRead
}

// Inspect accepts an inspector function that has same arguments as the TransactionManager.RunRepeatableRead
func (mmRunRepeatableRead *mTransactionManagerMockRunRepeatableRead) Inspect(f func(ctx context.Context, f func(ctxTX context.Context) error)) *mTransactionManagerMockRunRepeatableRead {
	if mmRunRepeatableRead.mock.inspectFuncRunRepeatableRead != nil {
		mmRunRepeatableRead.mock.t.Fatalf("Inspect function is already set for TransactionManagerMock.RunRepeatableRead")
	}

	mmRunRepeatableRead.mock.inspectFuncRunRepeatableRead = f

	return mmRunRepeatableRead
}

// Return sets up results that will be returned by TransactionManager.RunRepeatableRead
func (mmRunRepeatableRead *mTransactionManagerMockRunRepeatableRead) Return(err error) *TransactionManagerMock {
	if mmRunRepeatableRead.mock.funcRunRepeatableRead != nil {
		mmRunRepeatableRead.mock.t.Fatalf("TransactionManagerMock.RunRepeatableRead mock is already set by Set")
	}

	if mmRunRepeatableRead.defaultExpectation == nil {
		mmRunRepeatableRead.defaultExpectation = &TransactionManagerMockRunRepeatableReadExpectation{mock: mmRunRepeatableRead.mock}
	}
	mmRunRepeatableRead.defaultExpectation.results = &TransactionManagerMockRunRepeatableReadResults{err}
	return mmRunRepeatableRead.mock
}

// Set uses given function f to mock the TransactionManager.RunRepeatableRead method
func (mmRunRepeatableRead *mTransactionManagerMockRunRepeatableRead) Set(f func(ctx context.Context, f func(ctxTX context.Context) error) (err error)) *TransactionManagerMock {
	if mmRunRepeatableRead.defaultExpectation != nil {
		mmRunRepeatableRead.mock.t.Fatalf("Default expectation is already set for the TransactionManager.RunRepeatableRead method")
	}

	if len(mmRunRepeatableRead.expectations) > 0 {
		mmRunRepeatableRead.mock.t.Fatalf("Some expectations are already set for the TransactionManager.RunRepeatableRead method")
	}

	mmRunRepeatableRead.mock.funcRunRepeatableRead = f
	return mmRunRepeatableRead.mock
}

// When sets expectation for the TransactionManager.RunRepeatableRead which will trigger the result defined by the following
// Then helper
func (mmRunRepeatableRead *mTransactionManagerMockRunRepeatableRead) When(ctx context.Context, f func(ctxTX context.Context) error) *TransactionManagerMockRunRepeatableReadExpectation {
	if mmRunRepeatableRead.mock.funcRunRepeatableRead != nil {
		mmRunRepeatableRead.mock.t.Fatalf("TransactionManagerMock.RunRepeatableRead mock is already set by Set")
	}

	expectation := &TransactionManagerMockRunRepeatableReadExpectation{
		mock:   mmRunRepeatableRead.mock,
		params: &TransactionManagerMockRunRepeatableReadParams{ctx, f},
	}
	mmRunRepeatableRead.expectations = append(mmRunRepeatableRead.expectations, expectation)
	return expectation
}

// Then sets up TransactionManager.RunRepeatableRead return parameters for the expectation previously defined by the When method
func (e *TransactionManagerMockRunRepeatableReadExpectation) Then(err error) *TransactionManagerMock {
	e.results = &TransactionManagerMockRunRepeatableReadResults{err}
	return e.mock
}

// RunRepeatableRead implements transactor.TransactionManager
func (mmRunRepeatableRead *TransactionManagerMock) RunRepeatableRead(ctx context.Context, f func(ctxTX context.Context) error) (err error) {
	mm_atomic.AddUint64(&mmRunRepeatableRead.beforeRunRepeatableReadCounter, 1)
	defer mm_atomic.AddUint64(&mmRunRepeatableRead.afterRunRepeatableReadCounter, 1)

	if mmRunRepeatableRead.inspectFuncRunRepeatableRead != nil {
		mmRunRepeatableRead.inspectFuncRunRepeatableRead(ctx, f)
	}

	mm_params := &TransactionManagerMockRunRepeatableReadParams{ctx, f}

	// Record call args
	mmRunRepeatableRead.RunRepeatableReadMock.mutex.Lock()
	mmRunRepeatableRead.RunRepeatableReadMock.callArgs = append(mmRunRepeatableRead.RunRepeatableReadMock.callArgs, mm_params)
	mmRunRepeatableRead.RunRepeatableReadMock.mutex.Unlock()

	for _, e := range mmRunRepeatableRead.RunRepeatableReadMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmRunRepeatableRead.RunRepeatableReadMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRunRepeatableRead.RunRepeatableReadMock.defaultExpectation.Counter, 1)
		mm_want := mmRunRepeatableRead.RunRepeatableReadMock.defaultExpectation.params
		mm_got := TransactionManagerMockRunRepeatableReadParams{ctx, f}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRunRepeatableRead.t.Errorf("TransactionManagerMock.RunRepeatableRead got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRunRepeatableRead.RunRepeatableReadMock.defaultExpectation.results
		if mm_results == nil {
			mmRunRepeatableRead.t.Fatal("No results are set for the TransactionManagerMock.RunRepeatableRead")
		}
		return (*mm_results).err
	}
	if mmRunRepeatableRead.funcRunRepeatableRead != nil {
		return mmRunRepeatableRead.funcRunRepeatableRead(ctx, f)
	}
	mmRunRepeatableRead.t.Fatalf("Unexpected call to TransactionManagerMock.RunRepeatableRead. %v %v", ctx, f)
	return
}

// RunRepeatableReadAfterCounter returns a count of finished TransactionManagerMock.RunRepeatableRead invocations
func (mmRunRepeatableRead *TransactionManagerMock) RunRepeatableReadAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRunRepeatableRead.afterRunRepeatableReadCounter)
}

// RunRepeatableReadBeforeCounter returns a count of TransactionManagerMock.RunRepeatableRead invocations
func (mmRunRepeatableRead *TransactionManagerMock) RunRepeatableReadBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRunRepeatableRead.beforeRunRepeatableReadCounter)
}

// Calls returns a list of arguments used in each call to TransactionManagerMock.RunRepeatableRead.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRunRepeatableRead *mTransactionManagerMockRunRepeatableRead) Calls() []*TransactionManagerMockRunRepeatableReadParams {
	mmRunRepeatableRead.mutex.RLock()

	argCopy := make([]*TransactionManagerMockRunRepeatableReadParams, len(mmRunRepeatableRead.callArgs))
	copy(argCopy, mmRunRepeatableRead.callArgs)

	mmRunRepeatableRead.mutex.RUnlock()

	return argCopy
}

// MinimockRunRepeatableReadDone returns true if the count of the RunRepeatableRead invocations corresponds
// the number of defined expectations
func (m *TransactionManagerMock) MinimockRunRepeatableReadDone() bool {
	for _, e := range m.RunRepeatableReadMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.RunRepeatableReadMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterRunRepeatableReadCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRunRepeatableRead != nil && mm_atomic.LoadUint64(&m.afterRunRepeatableReadCounter) < 1 {
		return false
	}
	return true
}

// MinimockRunRepeatableReadInspect logs each unmet expectation
func (m *TransactionManagerMock) MinimockRunRepeatableReadInspect() {
	for _, e := range m.RunRepeatableReadMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TransactionManagerMock.RunRepeatableRead with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.RunRepeatableReadMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterRunRepeatableReadCounter) < 1 {
		if m.RunRepeatableReadMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to TransactionManagerMock.RunRepeatableRead")
		} else {
			m.t.Errorf("Expected call to TransactionManagerMock.RunRepeatableRead with params: %#v", *m.RunRepeatableReadMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRunRepeatableRead != nil && mm_atomic.LoadUint64(&m.afterRunRepeatableReadCounter) < 1 {
		m.t.Error("Expected call to TransactionManagerMock.RunRepeatableRead")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TransactionManagerMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockRunRepeatableReadInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TransactionManagerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TransactionManagerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockRunRepeatableReadDone()
}
